### ISSUE TITLE
service_sysvinit.j2 references tomcat

### ISSUE THREAD

**Issue by mdb** [silpion/ansible-heka#1]
The [service_sysvinit.j2](https://github.com/silpion/ansible-heka/blob/master/templates/service_sysvinit.j2#L3) file references "Tomcat" and "Tomcat application server."

Am I correct in assuming this is a typo?

Thanks!

**Comment by ghost** [comment]
Krchchch, yes, this looks pretty much like a copy/paste "issue". I've that fixed in next. Thank you :)
